### ISSUE TITLE
Error when compiling with GHC 8.6.5 Windows

### ISSUE THREAD

**Issue by ndmitchell** [shayne-fletcher/ghc-lib-parser-ex#38]
```
cbits\ghclib_api.h:28:10: error:
     error: #error Unsupported GHC API version
     #        error Unsupported GHC API version
              ^~~~~
   |
28 | #        error Unsupported GHC API version
   |          ^
`gcc.exe' failed in phase `C pre-processor'. (Exit code: 1)
```

**Comment by ndmitchell** [comment]
I was compiling the very latest 8.10 version.

**Comment by shayne-fletcher** [comment]
With this section enabled?
```
flags:
  hlint:
    ghc-lib: true
  ghc-lib-parser-ex:
    ghc-lib: true
```

**Comment by shayne-fletcher** [comment]
Be sure to pass the cabal flags `-f hlint:ghc-lib -f ghc-lib-parser-ex:ghc-lib`

**Comment by ndmitchell** [comment]
Would be much better if it just worked out the box on 8.6.5, since there's no chance of anyone manually setting flags.

**Comment by shayne-fletcher** [comment]
I understand. Maybe the way forward is if ghc-lib-parser-ex were to default to linking ghc-lib-parser unless told explicitly to link native-libs? Then,
```
  -- Unless explicitly told to link ghc-lib-parser, assume ghc native.
  if !flag(ghc-lib)
      build-depends:
        ghc,
        ghc-boot-th,
        ghc-boot
  else
      build-depends:
        ghc-lib-parser
```
would become,
```
  -- Unless explicitly told to link ghc-lib-parser, assume ghc native.
  if !flag(no-ghc-lib)
      build-depends:
        ghc,
        ghc-boot-th,
        ghc-boot
  else
      build-depends:
        ghc-lib-parser
```
That might be the better behavior?

**Comment by ndmitchell** [comment]
I would have thought ghc-lib-parser-ex-8.10 would link against ghc-8.10 when you are on 8.10, and when you aren't, use ghc-lib-parser, but have a flag to always link against ghc-lib-parser. That way you default to the right behaviour, and have a single flag to opt into using ghc-lib-parser even though you don't have to.

HLint probably needs to mirror those flags and defaults.

**Comment by shayne-fletcher** [comment]
> would have thought ghc-lib-parser-ex-8.10 would link against ghc-8.10 when you are on 8.10
How do you express that in the cabal file? Remember, ghc-lib-parser-ex supports all of 8.8, 8.10 and 8.11?

**Comment by ndmitchell** [comment]
Hmm. That makes it harder. I don't know... The end goal I think would be ideal is if HLint on GHC 8.10 didn't have to compile ghc-lib-parser (so it builds faster), but everywhere else it did (so I only have to support one interface). I also think that the ability to reuse the GHC package will be important for people who want to link against it using the GHC types directly. Not sure how you solve that - perhaps have ghc-lib-parser-ex default to 8.10, but have manual flags to make it always pick GHC (which would fail on 8.6) and always pick ghc-lib-parser (which always works).

**Comment by shayne-fletcher** [comment]
Yes. See the note in stack.yaml. Long story short, if you don't set the flags `hlint:ghc-lib` and `ghc-lib-parser-ex:ghc-lib`, both will link the native 8.10 libs if on 8.10 exactly as you want. If on a different version, `hlint` will auto link `ghc-lib-parser` but `ghc-lib-parse-ex` needs to be told to. So it's close but not quite as seamless as we'd like.

**Comment by shayne-fletcher** [comment]
Here's the note I'm talking about:
```
# Since we are compiling with 8.8.3, hlint will automatically link
# ghc-lib-parser rather than ghc native libs (since we target the 8.10
# parse tree). ghc-lib-parser-ex on the other hand will assume ghc
# native libs by default *for all ghc versions* unless told explicitly
# to link ghc-lib-parser. For clarity and consistency, force both.
flags:
  hlint:
    ghc-lib: true
  ghc-lib-parser-ex:
    ghc-lib: true
```
